### PR TITLE
added describe methods to  enable describe methods from the explorer

### PR DESCRIPTION
**Pull request by dgcaron**
with this PR you can right click on a stream or a table in the explorer and choose to descibe or describe extended. a new editor window will open showing the output of the action.

### CODE REVIEW

**Comment by rmoff** [comment]
thanks @dgcaron ! Can you bump the version number in package.json and update the changelog?

**Comment by dgcaron** [comment]
Anything else you want me to add?

**Comment by rmoff** [comment]
Apologies I’ve been on vacation - I’ll get to this today :)

**Comment by dgcaron** [comment]
my apologies then! hope you had a nice vacantion 👍

**Pull request merged**
