### PR TITLE
added ksql explorer, base structure for typescript classes and config.

### PR DESCRIPTION
**Pull request by dgcaron**
This is quite a lengthy PR due to the fact there was no language server yet.  the basic structure is generated using the generator ([link](https://code.visualstudio.com/docs/extensions/yocode)). now when you install the extension you get an icon in the activity bar (i used the kafka logo for now), and you can see the topics, streams and tables in your connected instance. you can refresh the explorer with `ctrl+shift+p` and choose the Refresh KSQL Explorer command.

ksql-explorer

you can configure the endpoint in the workspace config but defaults to localhost:8088. 

ksql-settings

if you like the PR and merge it in, i have more stuff to add. but i didn;t want to make the PR to bulky. stuff already in my local dev:
- describe stream or table from the explorer
- drop stream or table from the explorer

### CODE REVIEW

**Comment by rmoff** [comment]
@dgcaron thanks for this! I'm just trying it out locally, and can't get it to build. Can you suggest what I need to do? 

```
Robin@asgard02:dgcaron-vsc-ksql> vsce package
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ksql@0.0.2 compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ksql@0.0.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Robin/.npm/_logs/2018-08-20T16_29_45_069Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ksql@0.0.2 vscode:prepublish: `npm run compile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ksql@0.0.2 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Robin/.npm/_logs/2018-08-20T16_29_45_112Z-debug.log

Robin@asgard02:dgcaron-vsc-ksql> npm run compile

> ksql@0.0.2 compile /Users/Robin/git/dgcaron-vsc-ksql
> tsc -p ./

src/explorer/KSQLExplorerProvider.ts:3:81 - error TS2307: Cannot find module 'vscode'.

3 import { TreeDataProvider, TreeItem, ProviderResult, EventEmitter, Event } from 'vscode';
                                                                                  ~~~~~~~~


src/explorer/KSQLExplorerProvider.ts:40:48 - error TS2304: Cannot find name 'Thenable'.

40     getTreeItem(element: NodeBase): TreeItem | Thenable<TreeItem> {
                                                  ~~~~~~~~


src/explorer/models/nodeBase.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/explorer/models/StreamNode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/explorer/models/StreamsNode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/explorer/models/TableNode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/explorer/models/TablesNode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/explorer/models/TopicsNode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/KSQLConnectionConfig.ts:3:64 - error TS2307: Cannot find module 'vscode'.

3 import { WorkspaceConfiguration, workspace, window, Uri } from 'vscode';
                                                                 ~~~~~~~~


src/KSQLMain.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import * as vscode from 'vscode';
                          ~~~~~~~~


src/KSQLMode.ts:3:25 - error TS2307: Cannot find module 'vscode'.

3 import vscode = require('vscode');
                          ~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ksql@0.0.2 compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ksql@0.0.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Robin/.npm/_logs/2018-08-20T16_30_01_705Z-debug.log
```

**Comment by dgcaron** [comment]
Did you run 'npm install' in the root of the project?

**Comment by rmoff** [comment]
Got it, thanks 👍

**Comment by rmoff** [comment]
@dgcaron this is great, thank you! 🙇

**Comment by dgcaron** [comment]
glad you liked it! i did added that npm install instruction in the readme, but maybe in the wrong place?

**Comment by rmoff** [comment]
thanks, I saw it now :)

**Pull request merged**
