### PR TITLE
Added code to execute ksql against the vscode configured environment

### PR DESCRIPTION
**Pull request by dgcaron**
with this PR you can exectue a whole file or an selection by right clicking in a ksql file. it adds two menu items in the context menu of the editor. User feedback needs some more detailed attention but that can be added later. 

also fixed some linter issues

### CODE REVIEW

**Comment by rmoff** [comment]
OK makes sense. If it is easy to add some simple static output (e.g. "Statement executed") to the output window it would avoid any confusion.

**Comment by dgcaron** [comment]
Yes, will also add a toast on succesfull execution. Thanks for checking!

**Comment by dgcaron** [comment]
i removed the toasts and added an output channel.. this also paves the way to capture the output of an select statement.

**Comment by dgcaron** [comment]
don't merge this (yet), it is still Work in progress.

**Comment by dgcaron** [comment]
@rmoff  i have altered the behaviour (i believe for the better) can you give it a go? SELECT statements open a webview rendering the results. create, drop etc statements are rendered in an outputchannel.

**Comment by gAmUssA** [comment]
@dgcaron could you drop a quick note on how to test it locally?

**Comment by dgcaron** [comment]
Sure. That is all in the Readme.. Clone the repo, run npm install in the root of the project and hit debug. The extension will be configured against localhost, this can be changed in the ksql settings in vscode. 

When you open an file with an .ksql extension you can right click in the editor to run the whole file. If you select a part of a file you can run the selection.

**Comment by dgcaron** [comment]
@gAmUssA  did you manage to run the extension locally? do you need some additional help?

**Comment by rmoff** [comment]
@dgcaron sorry for the delay. I tested this again. 

1. `CREATE STREAM ratings WITH (KAFKA_TOPIC='ratings', VALUE_FORMAT='AVRO');` -> runs, but no output anywhere - where should I see it? 

2. `select * from ratings;` -> fails with `SELECT and PRINT queries must use the /query endpoint`

**Pull request closed without merging**
